name: Build and publish
on:
  push:
    tags:
      - "v*.*.*"  # Only trigger on tags like v1.2.3

jobs:
  build-and-release:
    name: Build EXE and Create Release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Apps with PyInstaller
        run: |
          pyinstaller --onefile --icon=iControl/logo.ico --add-data "iControl/static;static" --add-data "iControl/templates;templates" -n iControl iControl/main.py
          pyinstaller --windowed --onefile --icon=iAvisos/logo.ico --add-data "iAvisos/static;static" -n iAvisos iAvisos/main.py


      - name: Create GitHub Release with EXE
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.exe"
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }} - intraAxia4
          prerelease: false
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true